AWSTemplateFormatVersion: 2010-09-09
Description: Lambda function which retrieves the latest beta version from App Store Connect.
Parameters:
  Stack:
    Description: Stack name
    Type: String
    Default: mobile
  App:
    Description: Application name
    Type: String
    Default: live-app-versions
  Stage:
    Description: Stage name
    Type: String
    AllowedValues:
      - CODE
      - PROD
    Default: CODE
  AppleAppId:
    Description: The Apple id of the iOS app which will be polled against
    Type: String
  DeployBucket:
    Description: Bucket where RiffRaff uploads artifacts on deploy
    Type: String
    Default: mobile-dist
Resources:
  ExecutionRole:
    Type: AWS::IAM::Role
    Properties:
      AssumeRolePolicyDocument:
        Statement:
          - Effect: Allow
            Principal:
              Service:
                - lambda.amazonaws.com
            Action: sts:AssumeRole
      Path: /
      Policies:
        - PolicyName: logs
          PolicyDocument:
            Statement:
              Effect: Allow
              Action:
                - logs:CreateLogGroup
                - logs:CreateLogStream
                - logs:PutLogEvents
              Resource: arn:aws:logs:*:*:*
        - PolicyName: lambda
          PolicyDocument:
            Statement:
              Effect: Allow
              Action:
                - lambda:InvokeFunction
              Resource: "*"
        - PolicyName: privateConfiguration
          PolicyDocument:
            Statement:
              Effect: Allow
              Action:
                - ssm:GetParametersByPath
              Resource: !Sub arn:aws:ssm:${AWS::Region}:${AWS::AccountId}:parameter/${Stage}/${Stack}/${App}
  Lambda:
    Type: AWS::Lambda::Function
    Properties:
      FunctionName: !Sub ${App}-${Stage}
      Code:
        S3Bucket:
          Ref: DeployBucket
        S3Key: !Sub ${Stack}/${Stage}/${App}/${App}.jar
      Environment:
        Variables:
          Stage: !Ref Stage
          Stack: !Ref Stack
          App: !Ref App
          APPLE_APP_ID: !Ref AppleAppId
      Description: Lambda function which retrieves the latest beta version from App Store Connect.
      Handler: com.gu.liveappversions.Lambda::handler
      MemorySize: 128
      Role: !GetAtt ExecutionRole.Arn
      Runtime: java8
      Timeout: 60

  PollingEvent:
    Type: AWS::Events::Rule
    Properties:
      State: DISABLED
      Description: Triggers the lambda periodically, allowing us to check whether a new version has been released
      ScheduleExpression: rate(5 minutes)
      Targets:
        - Id: Lambda
          Arn: !GetAtt Lambda.Arn

  PollingEventLambdaPermission:
    Type: AWS::Lambda::Permission
    Properties:
      Action: lambda:InvokeFunction
      FunctionName: !GetAtt Lambda.Arn
      Principal: events.amazonaws.com
      SourceArn: !GetAtt PollingEvent.Arn