name: Build

on:
  push:
    branches:
      - main
  pull_request:
  workflow_dispatch:

# allow queued workflows to interrupt previous runs
concurrency:
  group: ${{ github.workflow }}-${{ github.event.number || github.ref }}
  cancel-in-progress: true

permissions:
  # Required by actions-riff-raff
  id-token: write
  contents: read
  # Required by actions-riff-raff to add comment to PR
  pull-requests: write

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v5

      - name: Setup JDK and sbt
        uses: guardian/setup-scala@v1

      - name: Clean, compile and test
        run: sbt clean compile test assembly

      - name: Upload to riff-raff
        uses: guardian/actions-riff-raff@v4
        with:
          githubToken: ${{ secrets.GITHUB_TOKEN }}
          roleArn: ${{ secrets.GU_RIFF_RAFF_ROLE_ARN }}
          app: live-app-versions
          buildNumberOffset: 172
          configPath: riff-raff.yaml
          contentDirectories: |
            live-app-versions:
              - target/scala-2.13/live-app-versions.jar
            live-app-versions-cfn:
              - cfn.yaml
